[build]
	command = "yarn build"
	functions = "functions"
	publish = "build"

[dev]
	framework = "#custom"
	command = "yarn start"
	targetPort = 3000
	port = 8888
	publish = "build"
	autoLaunch = true
